/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nabiki.ctp4j;

public class CThostFtdcSyncingInvestorPositionField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcSyncingInvestorPositionField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcSyncingInvestorPositionField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ThostFtdcCtpApiJNI.delete_CThostFtdcSyncingInvestorPositionField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInstrumentID(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_InstrumentID_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_InvestorID_get(swigCPtr, this);
  }

  public void setPosiDirection(char value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_PosiDirection_set(swigCPtr, this, value);
  }

  public char getPosiDirection() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_PosiDirection_get(swigCPtr, this);
  }

  public void setHedgeFlag(char value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_HedgeFlag_set(swigCPtr, this, value);
  }

  public char getHedgeFlag() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_HedgeFlag_get(swigCPtr, this);
  }

  public void setPositionDate(char value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_PositionDate_set(swigCPtr, this, value);
  }

  public char getPositionDate() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_PositionDate_get(swigCPtr, this);
  }

  public void setYdPosition(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_YdPosition_set(swigCPtr, this, value);
  }

  public int getYdPosition() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_YdPosition_get(swigCPtr, this);
  }

  public void setPosition(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_Position_set(swigCPtr, this, value);
  }

  public int getPosition() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_Position_get(swigCPtr, this);
  }

  public void setLongFrozen(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_LongFrozen_set(swigCPtr, this, value);
  }

  public int getLongFrozen() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_LongFrozen_get(swigCPtr, this);
  }

  public void setShortFrozen(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_ShortFrozen_set(swigCPtr, this, value);
  }

  public int getShortFrozen() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_ShortFrozen_get(swigCPtr, this);
  }

  public void setLongFrozenAmount(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_LongFrozenAmount_set(swigCPtr, this, value);
  }

  public double getLongFrozenAmount() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_LongFrozenAmount_get(swigCPtr, this);
  }

  public void setShortFrozenAmount(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_ShortFrozenAmount_set(swigCPtr, this, value);
  }

  public double getShortFrozenAmount() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_ShortFrozenAmount_get(swigCPtr, this);
  }

  public void setOpenVolume(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_OpenVolume_set(swigCPtr, this, value);
  }

  public int getOpenVolume() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_OpenVolume_get(swigCPtr, this);
  }

  public void setCloseVolume(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_CloseVolume_set(swigCPtr, this, value);
  }

  public int getCloseVolume() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_CloseVolume_get(swigCPtr, this);
  }

  public void setOpenAmount(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_OpenAmount_set(swigCPtr, this, value);
  }

  public double getOpenAmount() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_OpenAmount_get(swigCPtr, this);
  }

  public void setCloseAmount(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_CloseAmount_set(swigCPtr, this, value);
  }

  public double getCloseAmount() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_CloseAmount_get(swigCPtr, this);
  }

  public void setPositionCost(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_PositionCost_set(swigCPtr, this, value);
  }

  public double getPositionCost() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_PositionCost_get(swigCPtr, this);
  }

  public void setPreMargin(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_PreMargin_set(swigCPtr, this, value);
  }

  public double getPreMargin() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_PreMargin_get(swigCPtr, this);
  }

  public void setUseMargin(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_UseMargin_set(swigCPtr, this, value);
  }

  public double getUseMargin() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_UseMargin_get(swigCPtr, this);
  }

  public void setFrozenMargin(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_FrozenMargin_set(swigCPtr, this, value);
  }

  public double getFrozenMargin() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_FrozenMargin_get(swigCPtr, this);
  }

  public void setFrozenCash(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_FrozenCash_set(swigCPtr, this, value);
  }

  public double getFrozenCash() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_FrozenCash_get(swigCPtr, this);
  }

  public void setFrozenCommission(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_FrozenCommission_set(swigCPtr, this, value);
  }

  public double getFrozenCommission() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_FrozenCommission_get(swigCPtr, this);
  }

  public void setCashIn(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_CashIn_set(swigCPtr, this, value);
  }

  public double getCashIn() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_CashIn_get(swigCPtr, this);
  }

  public void setCommission(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_Commission_set(swigCPtr, this, value);
  }

  public double getCommission() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_Commission_get(swigCPtr, this);
  }

  public void setCloseProfit(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_CloseProfit_set(swigCPtr, this, value);
  }

  public double getCloseProfit() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_CloseProfit_get(swigCPtr, this);
  }

  public void setPositionProfit(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_PositionProfit_set(swigCPtr, this, value);
  }

  public double getPositionProfit() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_PositionProfit_get(swigCPtr, this);
  }

  public void setPreSettlementPrice(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_PreSettlementPrice_set(swigCPtr, this, value);
  }

  public double getPreSettlementPrice() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_PreSettlementPrice_get(swigCPtr, this);
  }

  public void setSettlementPrice(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_SettlementPrice_set(swigCPtr, this, value);
  }

  public double getSettlementPrice() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_SettlementPrice_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_TradingDay_get(swigCPtr, this);
  }

  public void setSettlementID(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_SettlementID_set(swigCPtr, this, value);
  }

  public int getSettlementID() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_SettlementID_get(swigCPtr, this);
  }

  public void setOpenCost(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_OpenCost_set(swigCPtr, this, value);
  }

  public double getOpenCost() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_OpenCost_get(swigCPtr, this);
  }

  public void setExchangeMargin(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_ExchangeMargin_set(swigCPtr, this, value);
  }

  public double getExchangeMargin() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_ExchangeMargin_get(swigCPtr, this);
  }

  public void setCombPosition(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_CombPosition_set(swigCPtr, this, value);
  }

  public int getCombPosition() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_CombPosition_get(swigCPtr, this);
  }

  public void setCombLongFrozen(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_CombLongFrozen_set(swigCPtr, this, value);
  }

  public int getCombLongFrozen() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_CombLongFrozen_get(swigCPtr, this);
  }

  public void setCombShortFrozen(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_CombShortFrozen_set(swigCPtr, this, value);
  }

  public int getCombShortFrozen() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_CombShortFrozen_get(swigCPtr, this);
  }

  public void setCloseProfitByDate(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_CloseProfitByDate_set(swigCPtr, this, value);
  }

  public double getCloseProfitByDate() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_CloseProfitByDate_get(swigCPtr, this);
  }

  public void setCloseProfitByTrade(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_CloseProfitByTrade_set(swigCPtr, this, value);
  }

  public double getCloseProfitByTrade() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_CloseProfitByTrade_get(swigCPtr, this);
  }

  public void setTodayPosition(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_TodayPosition_set(swigCPtr, this, value);
  }

  public int getTodayPosition() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_TodayPosition_get(swigCPtr, this);
  }

  public void setMarginRateByMoney(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_MarginRateByMoney_set(swigCPtr, this, value);
  }

  public double getMarginRateByMoney() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_MarginRateByMoney_get(swigCPtr, this);
  }

  public void setMarginRateByVolume(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_MarginRateByVolume_set(swigCPtr, this, value);
  }

  public double getMarginRateByVolume() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_MarginRateByVolume_get(swigCPtr, this);
  }

  public void setStrikeFrozen(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_StrikeFrozen_set(swigCPtr, this, value);
  }

  public int getStrikeFrozen() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_StrikeFrozen_get(swigCPtr, this);
  }

  public void setStrikeFrozenAmount(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_StrikeFrozenAmount_set(swigCPtr, this, value);
  }

  public double getStrikeFrozenAmount() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_StrikeFrozenAmount_get(swigCPtr, this);
  }

  public void setAbandonFrozen(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_AbandonFrozen_set(swigCPtr, this, value);
  }

  public int getAbandonFrozen() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_AbandonFrozen_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_ExchangeID_get(swigCPtr, this);
  }

  public void setYdStrikeFrozen(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_YdStrikeFrozen_set(swigCPtr, this, value);
  }

  public int getYdStrikeFrozen() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_YdStrikeFrozen_get(swigCPtr, this);
  }

  public void setInvestUnitID(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_InvestUnitID_set(swigCPtr, this, value);
  }

  public String getInvestUnitID() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_InvestUnitID_get(swigCPtr, this);
  }

  public void setPositionCostOffset(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_PositionCostOffset_set(swigCPtr, this, value);
  }

  public double getPositionCostOffset() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_PositionCostOffset_get(swigCPtr, this);
  }

  public void setTasPosition(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_TasPosition_set(swigCPtr, this, value);
  }

  public int getTasPosition() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_TasPosition_get(swigCPtr, this);
  }

  public void setTasPositionCost(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_TasPositionCost_set(swigCPtr, this, value);
  }

  public double getTasPositionCost() {
    return ThostFtdcCtpApiJNI.CThostFtdcSyncingInvestorPositionField_TasPositionCost_get(swigCPtr, this);
  }

  public CThostFtdcSyncingInvestorPositionField() {
    this(ThostFtdcCtpApiJNI.new_CThostFtdcSyncingInvestorPositionField(), true);
  }

}
