/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nabiki.ctp4j;

public class CThostFtdcQryMulticastInstrumentField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcQryMulticastInstrumentField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcQryMulticastInstrumentField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ThostFtdcCtpApiJNI.delete_CThostFtdcQryMulticastInstrumentField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTopicID(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcQryMulticastInstrumentField_TopicID_set(swigCPtr, this, value);
  }

  public int getTopicID() {
    return ThostFtdcCtpApiJNI.CThostFtdcQryMulticastInstrumentField_TopicID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcQryMulticastInstrumentField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return ThostFtdcCtpApiJNI.CThostFtdcQryMulticastInstrumentField_InstrumentID_get(swigCPtr, this);
  }

  public CThostFtdcQryMulticastInstrumentField() {
    this(ThostFtdcCtpApiJNI.new_CThostFtdcQryMulticastInstrumentField(), true);
  }

}
