/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nabiki.ctp4j;

public class CThostFtdcForQuoteParamField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcForQuoteParamField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcForQuoteParamField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ThostFtdcCtpApiJNI.delete_CThostFtdcForQuoteParamField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcForQuoteParamField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ThostFtdcCtpApiJNI.CThostFtdcForQuoteParamField_BrokerID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcForQuoteParamField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return ThostFtdcCtpApiJNI.CThostFtdcForQuoteParamField_InstrumentID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcForQuoteParamField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return ThostFtdcCtpApiJNI.CThostFtdcForQuoteParamField_ExchangeID_get(swigCPtr, this);
  }

  public void setLastPrice(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcForQuoteParamField_LastPrice_set(swigCPtr, this, value);
  }

  public double getLastPrice() {
    return ThostFtdcCtpApiJNI.CThostFtdcForQuoteParamField_LastPrice_get(swigCPtr, this);
  }

  public void setPriceInterval(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcForQuoteParamField_PriceInterval_set(swigCPtr, this, value);
  }

  public double getPriceInterval() {
    return ThostFtdcCtpApiJNI.CThostFtdcForQuoteParamField_PriceInterval_get(swigCPtr, this);
  }

  public CThostFtdcForQuoteParamField() {
    this(ThostFtdcCtpApiJNI.new_CThostFtdcForQuoteParamField(), true);
  }

}
