/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nabiki.ctp4j;

public class CThostFtdcSuperUserField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcSuperUserField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcSuperUserField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ThostFtdcCtpApiJNI.delete_CThostFtdcSuperUserField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUserID(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcSuperUserField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return ThostFtdcCtpApiJNI.CThostFtdcSuperUserField_UserID_get(swigCPtr, this);
  }

  public void setUserName(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcSuperUserField_UserName_set(swigCPtr, this, value);
  }

  public String getUserName() {
    return ThostFtdcCtpApiJNI.CThostFtdcSuperUserField_UserName_get(swigCPtr, this);
  }

  public void setPassword(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcSuperUserField_Password_set(swigCPtr, this, value);
  }

  public String getPassword() {
    return ThostFtdcCtpApiJNI.CThostFtdcSuperUserField_Password_get(swigCPtr, this);
  }

  public void setIsActive(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcSuperUserField_IsActive_set(swigCPtr, this, value);
  }

  public int getIsActive() {
    return ThostFtdcCtpApiJNI.CThostFtdcSuperUserField_IsActive_get(swigCPtr, this);
  }

  public CThostFtdcSuperUserField() {
    this(ThostFtdcCtpApiJNI.new_CThostFtdcSuperUserField(), true);
  }

}
