/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nabiki.ctp4j;

public class CThostFtdcReserveOpenAccountField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcReserveOpenAccountField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcReserveOpenAccountField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ThostFtdcCtpApiJNI.delete_CThostFtdcReserveOpenAccountField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTradeCode(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_TradeCode_set(swigCPtr, this, value);
  }

  public String getTradeCode() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_TradeCode_get(swigCPtr, this);
  }

  public void setBankID(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_BankID_set(swigCPtr, this, value);
  }

  public String getBankID() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_BankID_get(swigCPtr, this);
  }

  public void setBankBranchID(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_BankBranchID_set(swigCPtr, this, value);
  }

  public String getBankBranchID() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_BankBranchID_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_BrokerID_get(swigCPtr, this);
  }

  public void setBrokerBranchID(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_BrokerBranchID_set(swigCPtr, this, value);
  }

  public String getBrokerBranchID() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_BrokerBranchID_get(swigCPtr, this);
  }

  public void setTradeDate(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_TradeDate_set(swigCPtr, this, value);
  }

  public String getTradeDate() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_TradeDate_get(swigCPtr, this);
  }

  public void setTradeTime(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_TradeTime_set(swigCPtr, this, value);
  }

  public String getTradeTime() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_TradeTime_get(swigCPtr, this);
  }

  public void setBankSerial(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_BankSerial_set(swigCPtr, this, value);
  }

  public String getBankSerial() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_BankSerial_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_TradingDay_get(swigCPtr, this);
  }

  public void setPlateSerial(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_PlateSerial_set(swigCPtr, this, value);
  }

  public int getPlateSerial() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_PlateSerial_get(swigCPtr, this);
  }

  public void setLastFragment(char value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_LastFragment_set(swigCPtr, this, value);
  }

  public char getLastFragment() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_LastFragment_get(swigCPtr, this);
  }

  public void setSessionID(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_SessionID_set(swigCPtr, this, value);
  }

  public int getSessionID() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_SessionID_get(swigCPtr, this);
  }

  public void setCustomerName(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_CustomerName_set(swigCPtr, this, value);
  }

  public String getCustomerName() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_CustomerName_get(swigCPtr, this);
  }

  public void setIdCardType(char value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_IdCardType_set(swigCPtr, this, value);
  }

  public char getIdCardType() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_IdCardType_get(swigCPtr, this);
  }

  public void setIdentifiedCardNo(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_IdentifiedCardNo_set(swigCPtr, this, value);
  }

  public String getIdentifiedCardNo() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_IdentifiedCardNo_get(swigCPtr, this);
  }

  public void setGender(char value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_Gender_set(swigCPtr, this, value);
  }

  public char getGender() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_Gender_get(swigCPtr, this);
  }

  public void setCountryCode(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_CountryCode_set(swigCPtr, this, value);
  }

  public String getCountryCode() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_CountryCode_get(swigCPtr, this);
  }

  public void setCustType(char value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_CustType_set(swigCPtr, this, value);
  }

  public char getCustType() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_CustType_get(swigCPtr, this);
  }

  public void setAddress(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_Address_set(swigCPtr, this, value);
  }

  public String getAddress() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_Address_get(swigCPtr, this);
  }

  public void setZipCode(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_ZipCode_set(swigCPtr, this, value);
  }

  public String getZipCode() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_ZipCode_get(swigCPtr, this);
  }

  public void setTelephone(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_Telephone_set(swigCPtr, this, value);
  }

  public String getTelephone() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_Telephone_get(swigCPtr, this);
  }

  public void setMobilePhone(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_MobilePhone_set(swigCPtr, this, value);
  }

  public String getMobilePhone() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_MobilePhone_get(swigCPtr, this);
  }

  public void setFax(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_Fax_set(swigCPtr, this, value);
  }

  public String getFax() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_Fax_get(swigCPtr, this);
  }

  public void setEMail(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_EMail_set(swigCPtr, this, value);
  }

  public String getEMail() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_EMail_get(swigCPtr, this);
  }

  public void setMoneyAccountStatus(char value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_MoneyAccountStatus_set(swigCPtr, this, value);
  }

  public char getMoneyAccountStatus() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_MoneyAccountStatus_get(swigCPtr, this);
  }

  public void setBankAccount(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_BankAccount_set(swigCPtr, this, value);
  }

  public String getBankAccount() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_BankAccount_get(swigCPtr, this);
  }

  public void setBankPassWord(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_BankPassWord_set(swigCPtr, this, value);
  }

  public String getBankPassWord() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_BankPassWord_get(swigCPtr, this);
  }

  public void setInstallID(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_InstallID_set(swigCPtr, this, value);
  }

  public int getInstallID() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_InstallID_get(swigCPtr, this);
  }

  public void setVerifyCertNoFlag(char value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_VerifyCertNoFlag_set(swigCPtr, this, value);
  }

  public char getVerifyCertNoFlag() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_VerifyCertNoFlag_get(swigCPtr, this);
  }

  public void setCurrencyID(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_CurrencyID_set(swigCPtr, this, value);
  }

  public String getCurrencyID() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_CurrencyID_get(swigCPtr, this);
  }

  public void setDigest(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_Digest_set(swigCPtr, this, value);
  }

  public String getDigest() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_Digest_get(swigCPtr, this);
  }

  public void setBankAccType(char value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_BankAccType_set(swigCPtr, this, value);
  }

  public char getBankAccType() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_BankAccType_get(swigCPtr, this);
  }

  public void setBrokerIDByBank(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_BrokerIDByBank_set(swigCPtr, this, value);
  }

  public String getBrokerIDByBank() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_BrokerIDByBank_get(swigCPtr, this);
  }

  public void setTID(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_TID_set(swigCPtr, this, value);
  }

  public int getTID() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_TID_get(swigCPtr, this);
  }

  public void setReserveOpenAccStas(char value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_ReserveOpenAccStas_set(swigCPtr, this, value);
  }

  public char getReserveOpenAccStas() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_ReserveOpenAccStas_get(swigCPtr, this);
  }

  public void setErrorID(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_ErrorID_set(swigCPtr, this, value);
  }

  public int getErrorID() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_ErrorID_get(swigCPtr, this);
  }

  public void setErrorMsg(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_ErrorMsg_set(swigCPtr, this, value);
  }

  public String getErrorMsg() {
    return ThostFtdcCtpApiJNI.CThostFtdcReserveOpenAccountField_ErrorMsg_get(swigCPtr, this);
  }

  public CThostFtdcReserveOpenAccountField() {
    this(ThostFtdcCtpApiJNI.new_CThostFtdcReserveOpenAccountField(), true);
  }

}
