/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nabiki.ctp4j;

public class CThostFtdcStrikeOffsetField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcStrikeOffsetField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcStrikeOffsetField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ThostFtdcCtpApiJNI.delete_CThostFtdcStrikeOffsetField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInstrumentID(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcStrikeOffsetField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return ThostFtdcCtpApiJNI.CThostFtdcStrikeOffsetField_InstrumentID_get(swigCPtr, this);
  }

  public void setInvestorRange(char value) {
    ThostFtdcCtpApiJNI.CThostFtdcStrikeOffsetField_InvestorRange_set(swigCPtr, this, value);
  }

  public char getInvestorRange() {
    return ThostFtdcCtpApiJNI.CThostFtdcStrikeOffsetField_InvestorRange_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcStrikeOffsetField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ThostFtdcCtpApiJNI.CThostFtdcStrikeOffsetField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ThostFtdcCtpApiJNI.CThostFtdcStrikeOffsetField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ThostFtdcCtpApiJNI.CThostFtdcStrikeOffsetField_InvestorID_get(swigCPtr, this);
  }

  public void setOffset(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcStrikeOffsetField_Offset_set(swigCPtr, this, value);
  }

  public double getOffset() {
    return ThostFtdcCtpApiJNI.CThostFtdcStrikeOffsetField_Offset_get(swigCPtr, this);
  }

  public void setOffsetType(char value) {
    ThostFtdcCtpApiJNI.CThostFtdcStrikeOffsetField_OffsetType_set(swigCPtr, this, value);
  }

  public char getOffsetType() {
    return ThostFtdcCtpApiJNI.CThostFtdcStrikeOffsetField_OffsetType_get(swigCPtr, this);
  }

  public CThostFtdcStrikeOffsetField() {
    this(ThostFtdcCtpApiJNI.new_CThostFtdcStrikeOffsetField(), true);
  }

}
