/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nabiki.ctp4j;

public class CThostFtdcMarketDataLastMatchField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcMarketDataLastMatchField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcMarketDataLastMatchField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ThostFtdcCtpApiJNI.delete_CThostFtdcMarketDataLastMatchField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLastPrice(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcMarketDataLastMatchField_LastPrice_set(swigCPtr, this, value);
  }

  public double getLastPrice() {
    return ThostFtdcCtpApiJNI.CThostFtdcMarketDataLastMatchField_LastPrice_get(swigCPtr, this);
  }

  public void setVolume(int value) {
    ThostFtdcCtpApiJNI.CThostFtdcMarketDataLastMatchField_Volume_set(swigCPtr, this, value);
  }

  public int getVolume() {
    return ThostFtdcCtpApiJNI.CThostFtdcMarketDataLastMatchField_Volume_get(swigCPtr, this);
  }

  public void setTurnover(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcMarketDataLastMatchField_Turnover_set(swigCPtr, this, value);
  }

  public double getTurnover() {
    return ThostFtdcCtpApiJNI.CThostFtdcMarketDataLastMatchField_Turnover_get(swigCPtr, this);
  }

  public void setOpenInterest(double value) {
    ThostFtdcCtpApiJNI.CThostFtdcMarketDataLastMatchField_OpenInterest_set(swigCPtr, this, value);
  }

  public double getOpenInterest() {
    return ThostFtdcCtpApiJNI.CThostFtdcMarketDataLastMatchField_OpenInterest_get(swigCPtr, this);
  }

  public CThostFtdcMarketDataLastMatchField() {
    this(ThostFtdcCtpApiJNI.new_CThostFtdcMarketDataLastMatchField(), true);
  }

}
